# -*- mode: ruby -*-
# vi: set ft=ruby :



#Vagrant.configure("2") do |config|

Vagrant::Config.run do |config|

  config.vm.box = "centos64-plain"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"

#  config.vm.provision :shell, :path => "bootstrap.sh"

end
