# Bitcon server
#
# VERSION               0.0.1

FROM     base
MAINTAINER Jonas Colmsjö "jonas@gizur.com"

RUN apt-get update

VOLUME ["/var/volume1:volume1:ro"]

EXPOSE 8333 18333
CMD ["/start.sh",""]
